site_name: KWeaver官方技术手册
site_url: https://docs.kweaver.ai/
site_description: 价值驱动，认知智能走向开源共创

theme:
    name: material
    custom_dir: overrides
    palette:
        - scheme: default
          primary: indigo
          accent: indigo
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode
        - scheme: slate
          primary: black
          accent: indigo
          toggle:
              icon: material/brightness-4
              name: Switch to light mode
    font:
        text: Roboto
        code: Roboto Mono
    favicon: assets/favicon.png
    icon:
        logo: logo
        repo: fontawesome/brands/github
    features:
#      - navigation.tabs
#      - navigation.tabs.sticky
#      - navigation.expand
      - navigation.indexes
#      - navigation.sections
      - navigation.top
      - search.highlight
      - search.suggest
      - search.share
      - content.code.copy
      - content.code.annotate
      - navigation.footer
      - navigation.tracking
plugins:
  - meta-descriptions:
      export_csv: false
      quiet: false
      enable_checks: false
      min_length: 50
      max_length: 160
      trim: false
  - macros:
      # 替换默认的jinja宏标志{{}}，否则类似的地方可能报错
      # [[% raw %]]
      j2_block_start_string: '[[%'
      j2_block_end_string: '%]]'
      j2_variable_start_string: '[['
      j2_variable_end_string: ']]'
      # [[% endraw %]]
  - mike:
      # These fields are all optional; the defaults are as below...
      alias_type: symlink
      redirect_template: null
      deploy_prefix: ''
      canonical_version: null
      version_selector: true
      css_dir: css
      javascript_dir: js
  - search:
      lang:
        - zh
        - en
  - i18n:
      docs_structure: folder
      languages:
        - locale: zh
          name: 中文
          build: true
          default: true
        - locale: en
          name: English
          build: true
  - git-revision-date-localized: #最后更新时间
      type: iso_datetime

markdown_extensions:
  - admonition
  - abbr
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.keys
  - md_in_html
  - pymdownx.arithmatex:  # latex支持
      generic: true
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      # linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
#  - pymdownx.emoji:
#      emoji_index: !!python/name:material.extensions.emoji.twemoji
#      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - meta # 支持Markdown文件上方自定义标题标签等

#extra_javascript里有对数学公式的扩展，extra_css里是Css的知识了，及自定义网站格式颜色等
extra_javascript:
  - assets/extra.js
  - assets/mathjax.js
#  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - assets/tex-mml-chtml.js
  - assets/baidu-tongji.js
  - assets//busuanzi.pure.mini.js
extra_css:
  - assets/extra.css

# 代码仓库
repo_name: KWeaver
repo_url: https://github.com/AISHU-Technology/kweaver

extra:
  keywords: '认知智能, 领域框架, AGI时代'
  generator: false
  KWeaver:
    release: 0.2.0
  version:
    provider: mike
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: 中文
      lang: zh

# 底部日期
copyright: Copyright &copy; 2023 - 2024 Martin Donath

nav:
#  - index.md
  - 简介:
    - KWeaver介绍: introduction/about.md
    - 架构介绍: introduction/framework.md
  - 快速上手&部署文档:
    - 快速上手: getting_started/quick_start.md
    - 开发部署简介: getting_started/deploy_introduction.md
    - 部署手册:
      - 前端开发环境: deploy/front_deploy.md
      - 后端开发环境: deploy/backend_deploy.md
      - Docker-Compose部署: deploy/docker_compose.md
      - GPU部署: deploy/docker_gpu.md
      - K8S部署: deploy/docker_k8s.md
  - 知识进阶:
    - AI原生知识: advanced/AINative.md
    - Agent知识: advanced/agents.md
    - 大模型知识: advanced/big_models.md
    - 知识图谱: advanced/knowledge_graphs.md
  - API:
    - 模型工厂: api/models-factory.md
    - 知识网络: api/knowledge_graphs.md
    - 系统管理: api/system_management.md

  - FAQ:
    - 前端问题集锦: faq/front_errors.md
    - 后端问题集锦: faq/backend_errors.md
    - 部署问题集锦: faq/deploy_errors.md
    - 其他问题集锦: faq/other_errors.md
    - 常见状态码:
      - http状态码: error_code/http_status_code.md
      - KWeaver状态码: error_code/kw_status_code.md
  - 附录:
    - 词汇表: appendix/vocabulary.md
    - 版本日志: appendix/version_log.md
    - 联系我们: appendix/feedback.md