name: cicd
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: pip install mkdocs==1.6.0
      - run: pip install mkdocs-material==9.5.25
      - run: pip install mkdocs-material-extensions==1.3.1
      - run: pip install mkdocs-static-i18n==1.2.3
      - run: pip install mkdocs-macros-plugin==1.0.5
      - run: pip install mkdocs-git-revision-date-localized-plugin==1.2.6
      - run: pip install  mkdocs-meta-descriptions-plugin==3.0.0
      - run: pip install mike==2.1.2
      - run: git config --global user.name "${{ secrets.GIT_USER_NAME }}"
      - run: git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
#      - run: mike deploy --push --update-aliases 0.2.0
#      - run: mike set-default --push --update-aliases 0.2.0
      - run: mkdocs gh-deploy --force
