name: cicd
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: pip install mkdocs==1.6.0
      - run: pip install mkdocs-material
      - run: pip install mkdocs-static-i18n
      - run: pip install mkdocs-macros-plugin
      - run: pip install mkdocs-git-revision-date-localized-plugin
      - run: pip install mike
      - run: git config --global user.name "${{ secrets.GIT_USER_NAME }}"
      - run: git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
#      - run: git pull --rebase origin gh-pages
#      - run: mike deploy --push --update-aliases 0.2.0
      - run: mike deploy 0.2.0
      - run: mike set-default 0.2.0 -p
      - run: git push origin gh-pages:gh-pages --force
#      - run: mkdocs gh-deploy --force
